defaults:
  - model: LightGBM
  - _self_

raw:
  dir: data/raw
  name: LabeledTransactions.csv
  path: data/raw/LabeledTransactions.csv
  type: unicode

processed:
  dir: data/processed
  name: processed.csv
  path: ${processed.dir}/${processed.name}
  type: unicode
  ratio: 0.5

variables:
  drop_cols: ["acceptor_state", "pin_present"]
  num_vars: ["transaction_risk_score", "cc_amount", "ledger_balance"]
  num_idx: [1, 3, 4]
  cat_idx: [0, 2, 5, 6, 7, 8, 9, 10, 11, 12, 13]
  cat_num_vars:
    [
      "cardholder_presence",
      "card_presence",
      "partial_approval_capable",
      "hour",
      "month",
      "dayofweek",
      "year",
    ]
  cat_vars:
    [
      "channel",
      "processing_type",
      "cc_acceptor_state",
      "cc_acceptor_country",
      "cardholder_presence",
      "card_presence",
      "partial_approval_capable",
      "hour",
      "month",
      "dayofweek",
      "year",
    ]
